#!/usr/bin/env python
# coding=utf-8

import urllib
import BeautifulSoup

url = "http://www.freeformatter.com/mime-types-list.html"

data = urllib.urlopen(url).read()

out = open("autogenerated.go", "w")
out.write("package mime\n")
out.write("var mimes = map[string]string {\n")

soup = BeautifulSoup.BeautifulSoup(data)

table = soup.findAll("table")[0]

soup_table  = BeautifulSoup.BeautifulSoup(str(table))

trs = soup_table.findAll("tr")

all = {}

for tr in trs:
    soup_tr = BeautifulSoup.BeautifulSoup(str(tr))
    tds = soup_tr.findAll("td")
    if len(tds) == 0:
        continue
    if len(tds[1].contents) < 1 or len(tds[2].contents) < 1:
        continue
    if not tds[2].contents[0].startswith("."):
        continue
    mime = tds[1].contents[0]
    exts = tds[2].contents[0].split(",")
    for ext in exts:
        all[ext.strip()] = mime

#########################################################


url = "http://reference.sitepoint.com/html/mime-types-full"

data = urllib.urlopen(url).read()

soup = BeautifulSoup.BeautifulSoup(data)

table = soup.findAll("table")[0]

soup_table  = BeautifulSoup.BeautifulSoup(str(table))

trs = soup_table.findAll("tr")

for tr in trs:
    soup_tr = BeautifulSoup.BeautifulSoup(str(tr))
    tds = soup_tr.findAll("td")
    if len(tds) < 2:
        continue
    ext, mime = tds[0].contents[0], tds[1].contents[0]
    if ext not in all:
        print ext
        all[ext] = mime

print "========================="

########################################################

f = open("/etc/mime.types")
for line in f:
    if line[0] == "#":
        continue
    line = line.strip()
    if len(line) == 0:
        continue
    sp = line.split()
    if len(sp) < 2:
        continue
    for ext in sp[1:]:
        ext = "." + ext
        if ext not in all:
            print ext
            all[ext] = sp[0]

for ext in sorted(all.keys()):
    ext = ext.strip()
    out.write('\t"%s":"%s",\n'%(ext.lower(),all[ext]))

out.write("}\n")
out.close()
